#!/bin/sh

if [ ! -f "./build/gs++" ]; then
    echo "please build gs++ according to README"
    exit 1
fi

./build/gs++ \
    --host "0.0.0.0" \
    --port "50051" \
    --db "slpdb_test2" \
    --rpc_host "0.0.0.0" \
    --rpc_port "8332" \
    --rpc_user "user" \
    --rpc_pass "password919191828282777wq" \
#    --disable_slpsync          \
    --disable_utxo_chkpnt_load \
    --disable_utxo_chkpnt_save \
    --disable_utxosync         \
#    --disable_zmq              \
#    --disable_mongowatch       \
#    --disable_grpc             
